blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature request
    url: https://pact.canny.io
    about: The Canny board to send us feature requests, vote and measure the interest of users. Useful to submit a feature request when you have an idea but no concrete API design proposal.
  - name: â“ Simple question - Slack chat
    url: https://slack.pact.io
    about: If you have a simple question, or want to discuss a feature request, join our Slack chat.
  - name: â“ Simple question - Stack Overflow
    url: https://stackoverflow.com/questions/tagged/pact
    about: The GitHub issue tracker is not for technical support. Please use Stack Overflow, and ask the community for help.
  - name: â“ Advanced question - GitHub Discussions
    url: https://github.com/pact-foundation/pact-python/discussions
    about: Use GitHub Discussions for advanced and unanswered questions only, requiring a maintainer's answer. Make sure the question wasn't already asked.
