version: '3.9'

services:
  # A PostgreSQL database for the Broker to store Pacts and verification results
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  # The Pact Broker
  broker_app:
    # Alternatively the DiUS Pact Broker can be used:
    # image: dius/pact-broker
    #
    # As well as changing the image, the destination port will need to be changed
    # from 9292 below, and in the nginx.conf proxy_pass section
    image: pactfoundation/pact-broker:latest-multi
    ports:
      - "80:9292"
      - "9292:9292"
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
      PACT_BROKER_BASIC_AUTH_USERNAME: pactbroker
      PACT_BROKER_BASIC_AUTH_PASSWORD: pactbroker
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"
      PACT_BROKER_BASE_URL: 'https://localhost http://localhost http://localhost:9292 http://pact-broker:9292 https://host.docker.internal http://host.docker.internal http://host.docker.internal:9292'
    # The Pact Broker provides a healthcheck endpoint which we will use to wait
    # for it to become available before starting up
    healthcheck:
      test: [ "CMD", "wget", "-q", "--tries=1", "--spider", "http://pactbroker:pactbroker@localhost:9292/diagnostic/status/heartbeat" ]
      interval: 1s
      timeout: 2s
      retries: 5

  # An NGINX reverse proxy in front of the Broker on port 8443, to be able to
  # terminate with SSL
  nginx:
    image: nginx:alpine
    links:
      - broker_app:broker
    volumes:
      - ./ssl/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl
    ports:
      - "8443:443"
    restart: always
    depends_on:
      broker_app:
        condition: service_healthy
