---
name: SmartBear Supported Issue Label Added

on:
  issues:
    types:
      - labeled

jobs:
  call-workflow:
    uses: pact-foundation/.github/.github/workflows/smartbear-issue-label-added.yml@master
    permissions:
      issues: write
    secrets: inherit
